{
 "title": "Service Resource Overview",
 "tags": [
  "resources",
  "containers",
  "services",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "auth-service,smsf-be,smsf-fe,smsf-db"
   }
  ]
 },
 "panels": [
  {
   "title": "Server CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)) / count(node_cpu_seconds_total{mode=\"idle\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "Server Resources - CPU & Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Service Logs - auth-service (All Logs)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"$service\"}\n  | json\n  | line_format `[{{.level | upper | printf \"%-5s\"}}] │ {{.method | printf \"%-4s\"}} │ {{.path | printf \"%-30s\"}} │ {{.msg}} {{if .duration_ms}}({{.duration_ms}}ms){{end}}{{if .remote_addr}} | ip: {{.remote_addr}}{{end}}`"
    }
   ]
  },
  {
   "title": "Top API Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "auth_http_request_duration_seconds_sum{service=\"$service\"}",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "Top HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,sum by(status) (count_over_time({service=\"$service\",log_type=\"http\"} | json [5m])))"
    }
   ]
  }
 ]
}